version: '3.8'
services:
  client:
    build: ./client
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://host.docker.internal:5001
  server:
    build: ./server
    ports:
      - 5001:5001
